# Sensitive overrides for API keys and service endpoints.
#
# Copy this file to a secure location or update the placeholders below with
# the credentials required by your deployment. Keys defined here override the
# defaults used by the orchestrator components unless the corresponding
# environment variable (e.g. KIMI_API_KEY) is set.

api_keys:
  kimi: "SET_ME"

services:
  kimi:
    base_url: "https://api.moonshot.cn/v1"
    model: "kimi-k2-0905-preview"
